default: &default
  ip_whitelist: ['203.202.242.130', '120.50.7.126', '127.0.0.1']
  admins: ['khalid@nascenia.com', 'shaer@nascenia.com', 'faruk@nascenia.com', 'fuad@nascenia.com', 'masud@nascenia.com']
  year_range:
    start: 2010
    end: 2020
  services:
    team_planner:
      name: Team planner
      url: http://test.teamplanner.nascenia.com/
    knowledge_base:
      name: Knowledge base
      url: http://kb.nascenia.com/
    file_server:
      name: File server
      url: http://192.168.1.2/

development:
  <<: *default

staging:
  <<: *default
